version: '3.8'

services:
  ingestion-api:
    build:
      context: ./ingestion-api
    container_name: ingestion-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ferme
    depends_on:
      - db
    networks:
      - ferme-network

  db:
    build:
      context: ./database
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ferme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ferme-network


  sensor1:
    build:
      context: ./sensor
    container_name: sensor1
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=1
      - PLANT_ID=1
    networks:
      - ferme-network

  sensor2:
    build:
      context: ./sensor
    container_name: sensor2
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=2
      - PLANT_ID=2
    networks:
      - ferme-network

  sensor3:
    build:
      context: ./sensor
    container_name: sensor3
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=3
      - PLANT_ID=3
    networks:
      - ferme-network

  sensor4:
    build:
      context: ./sensor
    container_name: sensor4
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=4
      - PLANT_ID=4
    networks:
      - ferme-network

  sensor5:
    build:
      context: ./sensor
    container_name: sensor5
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=5
      - PLANT_ID=5
    networks:
      - ferme-network

  sensor6:
    build:
      context: ./sensor
    container_name: sensor6
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=6
      - PLANT_ID=6
    networks:
      - ferme-network

  sensor7:
    build:
      context: ./sensor
    container_name: sensor7
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=7
      - PLANT_ID=7
    networks:
      - ferme-network

  sensor8:
    build:
      context: ./sensor
    container_name: sensor8
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=8
      - PLANT_ID=8
    networks:
      - ferme-network

  detection:
    build:
      context: ./detection
    container_name: detection
    networks:
      - ferme-network

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    networks:
      - ferme-network

volumes:
  pgdata:

networks:
  ferme-network: