version: '3.8'

services:
  ingestion-api:
    image: yasia/ingestion-api:latest
    build:
      context: ./ingestion-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plant_monitoring
      - TZ=Europe/Paris
    depends_on:
      db:
        condition: service_healthy # attend que le service db soit "sain" avant de démarrer
    networks:
      - ferme-network

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=plant_monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d plant_monitoring"]
      interval: 10s
      timeout: 15s
      retries: 20
      start_period: 60s
    networks:
      - ferme-network

  # Capteurs français (FR-v8)
  sensor-fr-1:
    build: ./sensor
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=FR-001
      - SENSOR_VERSION=FR-v8
      - PLANT_ID=1
      - TZ=Europe/Paris
      - INTERVAL=10
    depends_on:
      ingestion-api:
        condition: service_started
    networks:
      - ferme-network

  sensor-fr-2:
    build: ./sensor
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=FR-002
      - SENSOR_VERSION=FR-v8
      - PLANT_ID=2
      - TZ=Europe/Paris
      - INTERVAL=15
    depends_on:
      ingestion-api:
        condition: service_started
    networks:
      - ferme-network

  # Capteurs anglais (EN-v2)
  sensor-en-1:
    build: ./sensor
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=EN-001
      - SENSOR_VERSION=EN-v2
      - PLANT_ID=1
      - TZ=Europe/Paris
      - INTERVAL=12
    depends_on:
      ingestion-api:
        condition: service_started
    networks:
      - ferme-network

  sensor-en-2:
    build: ./sensor
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=EN-002
      - SENSOR_VERSION=EN-v2
      - PLANT_ID=2
      - TZ=Europe/Paris
      - INTERVAL=8
    depends_on:
      ingestion-api:
        condition: service_started
    networks:
      - ferme-network

  detection:
    build: ./detection
    environment:
      - DB_HOST=db
      - DB_NAME=plant_monitoring
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TZ=Europe/Paris
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ferme-network

  dashboard:
    build: ./dashboard
    ports:
      - "8502:8501"
    environment:
      - TZ=Europe/Paris
    depends_on:
      - ingestion-api # dépendra du service ingestion-api pour garantir que les données soient disponibles.
    networks:
      - ferme-network

volumes:
  pgdata:

networks:
  ferme-network:
    name: ferme-network
    driver: bridge
    attachable: true
