version: '3.8'

services:
  ingestion-api:
    build:
      context: ./ingestion-api
    container_name: ingestion-api
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ferme
    depends_on:
      - db
    networks:
      - ferme-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ferme-network

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - ferme-network

  detection:
    build:
      context: ./detection
    container_name: detection
    depends_on:
      - db
    networks:
      - ferme-network

  sensor1:
    image: abelfodil/sensor:0.0.1
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SCENARIO_ID=1
    networks:
      - ferme-network

  sensor2:
    image: abelfodil/sensor:0.0.1
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SCENARIO_ID=2
    networks:
      - ferme-network

volumes:
  pgdata:

networks:
  ferme-network:

