version: '3.8'

services:
  ingestion-api:
    build:
      context: ./ingestion-api
    container_name: ingestion-api
    environment:
      - DATABASE_URL=postgresql://admin:secret@db:5432/ferme
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ferme-network

  db:
    build:
      context: ./database
    container_name: postgres-db
    environment:
      - POSTGRES_DB=ferme
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ferme-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  sensor1:
    build: ./sensor
    container_name: sensor1
    environment:
      - SERVER_URL=http://ingestion-api:8000/ingest
      - SENSOR_ID=1
      - PLANT_ID=1
    networks:
      - ferme-network

  detection:
    build: ./detection
    container_name: detection
    depends_on:
      - db
    networks:
      - ferme-network

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8502:8501"
    networks:
      - ferme-network

volumes:
  pgdata:

networks:
  ferme-network:

